FROM node:14.17.0-alpine

WORKDIR /webapp

COPY public ./public
COPY src ./src
COPY package.json ./package.json

RUN npm install
RUN npm run build

FROM nginx:stable-alpine

RUN ls

COPY ./dist /usr/share/nginx/html

RUN rm /etc/nginx/conf.d/default.conf

COPY nginx.conf /etc/nginx/conf.d

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
